# Generated by Django 5.2.7 on 2025-11-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0038_alter_unidad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinspeccion',
            name='es_dummy',
            field=models.BooleanField(default=False, verbose_name="Es un registro 'Solo Carga'"),
        ),
        migrations.AddField(
            model_name='llantasinspeccion',
            name='es_dummy',
            field=models.BooleanField(default=False, verbose_name="Es un registro 'Solo Carga'"),
        ),
    ]
