# Generated by Django 5.2.7 on 2025-11-11 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0039_checklistinspeccion_es_dummy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionrevision',
            name='refaccion',
            field=models.TextField(blank=True, null=True, verbose_name='Refacción Requerida'),
        ),
        migrations.AddField(
            model_name='asignacionrevision',
            name='tipo_programacion',
            field=models.CharField(choices=[('PROGRAMACION', 'Programación Normal'), ('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Mantenimiento Correctivo')], default='PROGRAMACION', max_length=12, verbose_name='Tipo de Programación'),
        ),
        migrations.AddField(
            model_name='asignacionrevision',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado (Correctivo)'),
        ),
        migrations.AlterField(
            model_name='asignacionrevision',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente (Normal)'), ('EN_PROCESO', 'En Proceso'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado'), ('NO_VINO', 'No Vino'), ('PREVENTIVO', 'Pendiente (Preventivo)'), ('CORRECTIVO', 'Pendiente (Correctivo)')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
    ]
