# Generated by Django 5.2.7 on 2025-11-11 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0040_asignacionrevision_refaccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionrevision',
            name='refaccion',
        ),
        migrations.RemoveField(
            model_name='asignacionrevision',
            name='usuario_asignado',
        ),
        migrations.CreateModel(
            name='TareaCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refaccion', models.TextField(verbose_name='Refacción o Tarea Requerida')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la Tarea')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_correctivas', to='flota.asignacionrevision')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_correctivas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Tarea Correctiva',
                'verbose_name_plural': 'Tareas Correctivas',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
