# Generated by Django 5.2.7 on 2025-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0041_remove_asignacionrevision_refaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareacorrectiva',
            name='piezas_utilizadas',
            field=models.TextField(blank=True, help_text='Ej: 2x Filtro Aire (AF255), 1x Balatas (B-12)', null=True, verbose_name='Piezas o Materiales Utilizados'),
        ),
        migrations.AlterField(
            model_name='tareacorrectiva',
            name='refaccion',
            field=models.TextField(verbose_name='Descripción de la Tarea'),
        ),
    ]
