# Generated by Django 5.2.7 on 2025-11-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0042_tareacorrectiva_piezas_utilizadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareacorrectiva',
            name='piezas_utilizadas',
        ),
    ]
