# Generated by Django 5.2.7 on 2025-11-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0043_remove_tareacorrectiva_piezas_utilizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llantasinspeccion',
            name='km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje en Inspección'),
        ),
    ]
