# Generated by Django 5.2.7 on 2025-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0044_alter_llantasinspeccion_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareacorrectiva',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('CORRECTIVO', 'Correctivo'), ('PREVENTIVO', 'Preventivo')], default='CORRECTIVO', max_length=12, verbose_name='Tipo de Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='asignacionrevision',
            name='tipo_programacion',
            field=models.CharField(choices=[('PROGRAMACION', 'Programación Normal'), ('FUERA_PROGRAMACION', 'Fuera de Programación')], default='PROGRAMACION', max_length=20, verbose_name='Tipo de Programación'),
        ),
    ]
