# Generated by Django 5.2.7 on 2025-11-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0045_tareacorrectiva_tipo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='foto_odometro',
        ),
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='foto_sticker',
        ),
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='foto_thermo_hrs',
        ),
        migrations.RemoveField(
            model_name='llantasinspeccion',
            name='km',
        ),
        migrations.AddField(
            model_name='cargadiesel',
            name='foto_odometro',
            field=models.ImageField(blank=True, null=True, upload_to='cargas_diesel/odometro/', verbose_name='Foto Odómetro (OCR)'),
        ),
        migrations.AddField(
            model_name='cargadiesel',
            name='foto_sticker',
            field=models.ImageField(blank=True, null=True, upload_to='cargas_diesel/sticker/', verbose_name='Foto Sticker'),
        ),
        migrations.AddField(
            model_name='cargadiesel',
            name='foto_thermo_hrs',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_thermo_hrs/', verbose_name='Foto Horas Thermo'),
        ),
    ]
