# Generated by Django 5.2.7 on 2025-11-19 15:10

import RH.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'División Operativa',
                'verbose_name_plural': 'Divisiones Operativas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MotivoInactivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Motivo de Inactivación',
                'verbose_name_plural': 'Motivos de Inactivación',
                'ordering': ['motivo'],
            },
        ),
        migrations.CreateModel(
            name='TipoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej. 'Licencia de Conducir', 'Certificado Médico'", max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requiere_fecha_vencimiento', models.BooleanField(default=False, help_text='Indica si este tipo de documento tiene una fecha de vencimiento.')),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Operador',
                'verbose_name_plural': 'Tipos de Documentos de Operador',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_empleado', models.CharField(blank=True, help_text='Número de empleado interno único', max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inactivacion', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Calle y número', max_length=255, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, default='México', max_length=50, null=True)),
                ('telefono_personal', models.CharField(blank=True, help_text='Formato: +999999999. Máx. 15 dígitos.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')])),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Viudo/a', 'Viudo/a'), ('Divorciado/a', 'Divorciado/a'), ('Unión Libre', 'Unión Libre')], max_length=20, null=True)),
                ('nacionalidad', models.CharField(blank=True, default='Mexicana', max_length=50, null=True)),
                ('curp', models.CharField(blank=True, help_text='CURP a 18 caracteres alfanuméricos.', max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de CURP inválido.', regex='^[A-Z]{4}[0-9]{6}[H,M][A-Z]{2}[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z]{2}$')])),
                ('rfc', models.CharField(blank=True, help_text='RFC a 12 o 13 caracteres alfanuméricos.', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RFC inválido.', regex='^[A-Z&Ñ]{3,4}[0-9]{6}[A-Z0-9]{3}$')])),
                ('nss', models.CharField(blank=True, help_text='Número de Seguro Social a 11 dígitos.', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NSS debe ser un número de 11 dígitos.', regex='^\\d{11}$')])),
                ('nombre_conyuge', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Cónyuge')),
                ('telefono_conyuge', models.CharField(blank=True, help_text='Formato: +999999999. Máx. 15 dígitos.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del Cónyuge')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to=RH.models.empleado_foto_perfil_path)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('clabe_interbancaria', models.CharField(blank=True, help_text='CLABE Interbancaria a 18 dígitos.', max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='La CLABE debe ser un número de 18 dígitos.', regex='^\\d{18}$')])),
                ('numero_cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, help_text='Número de tarjeta de débito/crédito a 16 dígitos.', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='El número de tarjeta debe ser de 16 dígitos.', regex='^\\d{16}$')], verbose_name='Número de Tarjeta')),
                ('nombre_referencia_1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_referencia_1', models.CharField(blank=True, max_length=15, null=True)),
                ('relacion_referencia_1', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_referencia_2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_referencia_2', models.CharField(blank=True, max_length=15, null=True)),
                ('relacion_referencia_2', models.CharField(blank=True, max_length=50, null=True)),
                ('ine_documento', models.FileField(blank=True, help_text='Copia de INE/Identificación oficial', null=True, upload_to=RH.models.empleado_ine_path)),
                ('comprobante_domicilio', models.FileField(blank=True, help_text='Comprobante de domicilio reciente', null=True, upload_to=RH.models.empleado_domicilio_path)),
                ('curriculum_vitae', models.FileField(blank=True, help_text='Currículum Vitae', null=True, upload_to=RH.models.empleado_cv_path)),
                ('acta_nacimiento_documento', models.FileField(blank=True, null=True, upload_to=RH.models.empleado_acta_nacimiento_path, verbose_name='Acta de Nacimiento')),
                ('comprobante_estudios_documento', models.FileField(blank=True, null=True, upload_to=RH.models.empleado_comprobante_estudios_path, verbose_name='Comprobante de Estudios')),
                ('carta_recomendacion_1_documento', models.FileField(blank=True, null=True, upload_to=RH.models.empleado_carta_recomendacion_1_path, verbose_name='Carta de Recomendación 1')),
                ('carta_recomendacion_2_documento', models.FileField(blank=True, null=True, upload_to=RH.models.empleado_carta_recomendacion_2_path, verbose_name='Carta de Recomendación 2')),
                ('constancia_fiscal_documento', models.FileField(blank=True, null=True, upload_to=RH.models.empleado_constancia_fiscal_path, verbose_name='Constancia Fiscal (RFC)')),
                ('aviso_retencion_infonavit_documento', models.FileField(blank=True, null=True, upload_to=RH.models.empleado_aviso_infonavit_path, verbose_name='Aviso de Retención de Infonavit')),
                ('semanas_cotizadas_imss_documento', models.FileField(blank=True, null=True, upload_to=RH.models.empleado_semanas_imss_path, verbose_name='Semanas Cotizadas IMSS')),
                ('empresa', models.CharField(blank=True, choices=[('MIGMAR', 'Migmar'), ('MARCO_MORALES', 'Marco Morales')], max_length=20, null=True, verbose_name='Empresa')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='RH.departamento')),
                ('division_operativa', models.ManyToManyField(blank=True, to='RH.divisionoperativa', verbose_name='División Operativa')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_a_cargo', to='RH.empleado')),
                ('motivo_inactivacion', models.ForeignKey(blank=True, help_text='Motivo por el cual el empleado fue inactivado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='RH.motivoinactivacion')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('DETERMINADO', 'Determinado'), ('INDETERMINADO', 'Indeterminado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text="Requerido solo si el contrato es de tipo 'Determinado'", null=True)),
                ('archivo_contrato', models.FileField(blank=True, null=True, upload_to=RH.models.contrato_documento_path, verbose_name='Archivo del Contrato')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='RH.empleado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='RH.empleado')),
            ],
            options={
                'verbose_name': 'Hijo',
                'verbose_name_plural': 'Hijos',
                'ordering': ['fecha_nacimiento'],
            },
        ),
        migrations.CreateModel(
            name='HistorialLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CAMBIO_PUESTO', 'Cambio de Puesto'), ('SUSPENSION', 'Suspensión'), ('INCAPACIDAD', 'Incapacidad'), ('ACTA_ADMINISTRATIVA', 'Acta Administrativa'), ('PERMISO', 'Permiso'), ('RECONTRATACION', 'Re-contratación'), ('RENUNCIA', 'Renuncia'), ('BAJA', 'Baja'), ('ABANDONO', 'Abandono')], max_length=50, verbose_name='Tipo de Evento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha del Evento / Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin (si aplica)')),
                ('puesto', models.CharField(blank=True, help_text='Nuevo puesto del empleado.', max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, help_text='Nuevo departamento del empleado.', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Observaciones')),
                ('motivo_salida', models.CharField(blank=True, choices=[('Renuncia', [('AMBIENTE_LABORAL', 'Ambiente laboral'), ('LIDERAZGO_RENUNCIA', 'Liderazgo'), ('MOTIVOS_PERSONALES', 'Motivos personales'), ('PRESTACIONES', 'Prestaciones')]), ('Baja', [('RESICION_CONTRATO', 'Rescisión de Contrato'), ('FALTAS_REGLAMENTO', 'Faltas al Reglamento'), ('TERMINO_CONTRATO', 'Término de Contrato'), ('BAJO_RENDIMIENTO', 'Bajo Rendimiento')]), ('Abandono', [('FALTAS_INJUSTIFICADAS', 'Faltas injustificadas'), ('LIDERAZGO_ABANDONO', 'Liderazgo'), ('PAGO', 'Pago')])], help_text='Detallar el motivo si el evento es una Renuncia, Baja o Abandono.', max_length=50, null=True)),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to=RH.models.historial_documento_path, verbose_name='Adjuntar Documento')),
                ('estatus', models.CharField(choices=[('BUSCANDO', 'Buscando Reemplazo'), ('REMPLAZADO', 'Reemplazado')], default='BUSCANDO', max_length=20, verbose_name='Estatus de la Vacante')),
                ('fecha_reemplazo', models.DateField(blank=True, null=True, verbose_name='Fecha de Asignación del Reemplazo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_laboral_eventos', to='RH.empleado')),
                ('reemplazo', models.ForeignKey(blank=True, help_text='Empleado que cubre esta vacante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplaza_a', to='RH.empleado')),
            ],
            options={
                'verbose_name': 'Evento de Historial Laboral',
                'verbose_name_plural': 'Eventos de Historial Laboral',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del puesto (ej. 'Gerente de Ventas', 'Operador de Tráfico')", max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del puesto.', null=True)),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, help_text='Salario base mensual para este puesto.', max_digits=10, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_en_puesto', to='RH.puesto'),
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_efectiva', models.DateField(help_text='Fecha a partir de la cual este salario es efectivo.')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarios', to='RH.empleado')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'ordering': ['-fecha_efectiva'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_carga',
            field=models.ManyToManyField(blank=True, to='RH.tipocarga', verbose_name='Tipo de Carga'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_viaje',
            field=models.ManyToManyField(blank=True, to='RH.tipoviaje', verbose_name='Tipo de Viaje'),
        ),
        migrations.CreateModel(
            name='DocumentoOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=RH.models.operador_documento_path)),
                ('numero_documento', models.CharField(blank=True, help_text='Número de licencia, folio, etc.', max_length=100, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_operador', to='RH.empleado')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RH.tipodocumentooperador')),
            ],
            options={
                'verbose_name': 'Documento de Operador',
                'verbose_name_plural': 'Documentos de Operador',
                'ordering': ['empleado__apellido', 'empleado__nombre', 'tipo_documento__nombre'],
                'unique_together': {('empleado', 'tipo_documento', 'numero_documento')},
            },
        ),
    ]
