# Generated by Django 5.2.7 on 2025-11-18 22:05

import RH.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='ine_frente',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='ine_reverso',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='licencia',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=RH.models.empleado_foto_perfil_path),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_en_puesto', to='RH.puesto'),
        ),
    ]
