# Generated by Django 5.2.7 on 2025-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(default=1, max_length=150, verbose_name='Puesto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiallaboral',
            name='departamento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Departamento'),
        ),
    ]
