# Generated by Django 5.2.7 on 2025-11-19 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0002_remove_empleado_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
