# Generated by Django 5.2.7 on 2025-11-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_diesel', models.DecimalField(decimal_places=2, default=24.5, max_digits=6, verbose_name='Precio Diésel')),
                ('costo_km_llantas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Costo Llantas/KM')),
                ('costo_km_mantenimiento', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Costo Mtto/KM')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetros Globales',
                'verbose_name_plural': 'Parámetros Globales',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Eco / Unidad')),
                ('rendimiento_cargado', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Rendimiento Cargado (km/l)')),
                ('rendimiento_vacio', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Rendimiento Vacío (km/l)')),
                ('costo_seguro_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_gps_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciacion_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('otros_fijos_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia_km_ida', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distancia Ida (KM)')),
                ('es_viaje_redondo', models.BooleanField(default=True)),
                ('regreso_cargado', models.BooleanField(default=False)),
                ('dias_viaje', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Días de Viaje')),
                ('costo_casetas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sueldo_operador', models.DecimalField(decimal_places=2, max_digits=10)),
                ('viaticos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_maniobras', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margen_utilidad_deseado', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Margen (%)')),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador_automatico.cliente')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_automatico.unidad')),
            ],
        ),
    ]
