# Generated by Django 5.2.7 on 2025-11-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_automatico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='capacidad_maxima_unidad',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5, verbose_name='Capacidad Max Unidad (Ton)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='costo_hora_demora',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8, verbose_name='Costo x Hora Demora'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='factor_terreno',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Factor Terreno'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='horas_espera_carga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas Espera Carga'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='horas_espera_descarga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas Espera Descarga'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='peso_carga_toneladas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Peso Carga (Ton)'),
        ),
    ]
