# Generated by Django 5.2.7 on 2025-11-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_automatico', '0002_cotizacion_capacidad_maxima_unidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='capacidad_maxima_unidad',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='costo_hora_demora',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='factor_terreno',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='horas_espera_carga',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='horas_espera_descarga',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='peso_carga_toneladas',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='regreso_cargado',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='costo_gps_mensual',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='costo_seguro_mensual',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='depreciacion_mensual',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='otros_fijos_mensual',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='es_refrigerado',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Thermo?'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='horas_thermo_motor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas uso Thermo'),
        ),
        migrations.AddField(
            model_name='parametrosglobales',
            name='consumo_thermo_hora',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4, verbose_name='Litros/Hora Thermo'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='costo_fijo_mensual_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Suma Costos Fijos (Seguro+GPS+Deprec)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='dias_viaje',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Días Totales de Viaje'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='es_viaje_redondo',
            field=models.BooleanField(default=True, verbose_name='¿Es viaje redondo?'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='margen_utilidad_deseado',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Margen Deseado (%)'),
        ),
        migrations.AlterField(
            model_name='parametrosglobales',
            name='costo_km_llantas',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Desgaste Llantas ($/Km)'),
        ),
        migrations.AlterField(
            model_name='parametrosglobales',
            name='costo_km_mantenimiento',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Reserva Mtto ($/Km)'),
        ),
        migrations.AlterField(
            model_name='parametrosglobales',
            name='precio_diesel',
            field=models.DecimalField(decimal_places=2, default=24.5, max_digits=6, verbose_name='Precio Diésel ($/L)'),
        ),
    ]
