# Generated by Django 5.2.7 on 2025-11-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_automatico', '0003_remove_cotizacion_capacidad_maxima_unidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Razón Social / Nombre'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='costo_casetas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Casetas (Total)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='costo_maniobras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maniobras / Cargas'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='dias_viaje',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Días de Operación'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='es_refrigerado',
            field=models.BooleanField(default=False, verbose_name='¿Servicio Refrigerado?'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='es_viaje_redondo',
            field=models.BooleanField(default=True, verbose_name='¿Cobrar Redondo?'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='horas_thermo_motor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas Uso Thermo'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='margen_utilidad_deseado',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Margen Objetivo (%)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='sueldo_operador',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo Operador'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='viaticos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Viáticos / Comidas'),
        ),
        migrations.AlterField(
            model_name='parametrosglobales',
            name='consumo_thermo_hora',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4, verbose_name='Consumo Thermo (Lts/Hora)'),
        ),
        migrations.AlterField(
            model_name='parametrosglobales',
            name='costo_km_llantas',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Factor Desgaste Llantas ($/Km)'),
        ),
        migrations.AlterField(
            model_name='parametrosglobales',
            name='costo_km_mantenimiento',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Reserva Mantenimiento ($/Km)'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='costo_fijo_mensual_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costos Fijos Mensuales (Seguro+GPS+Placas)'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Unidad / Económico'),
        ),
    ]
