# Generated by Django 5.2.7 on 2025-11-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_automatico', '0004_remove_cliente_email_remove_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='costo_fijo_mensual_total',
        ),
        migrations.AddField(
            model_name='unidad',
            name='costo_gps_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='GPS / Satelital'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='costo_seguro_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Seguro Mensual'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='depreciacion_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depreciación Mensual'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='otros_fijos_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otros (Placas/Admin)'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(help_text='Ej. Tracto T-800', max_length=50, verbose_name='Eco / Unidad'),
        ),
    ]
