# Generated by Django 5.2.7 on 2025-11-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_alter_tareapreventivasubtask_foto_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='status',
            field=models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('PENDIENTE_CIERRE', 'Pendiente de Cierre'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ASIGNADA', max_length=20, verbose_name='Estado'),
        ),
    ]
