# Generated by Django 5.2.7 on 2025-11-12 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Artículo')),
                ('numero_proveedor', models.CharField(blank=True, max_length=100, verbose_name='Número de Proveedor')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='almacen/fotos/', verbose_name='Foto')),
                ('stock_total', models.PositiveIntegerField(default=0, editable=False, verbose_name='Stock Disponible')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra (Unitario)')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('tipo', models.CharField(choices=[('Stock', 'Para Almacén (Stock)'), ('Unidad', 'Asignado a Unidad')], default='Stock', max_length=10, verbose_name='Tipo de Entrada')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='almacen.articulo')),
            ],
            options={
                'verbose_name': 'Entrada de Artículo',
                'verbose_name_plural': 'Entradas de Artículos',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.proveedor'),
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='almacen.categoria')),
            ],
            options={
                'verbose_name': 'Sub-categoría',
                'verbose_name_plural': 'Sub-categorías',
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='almacen.subcategoria', verbose_name='Sub-categoría'),
        ),
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together={('nombre', 'subcategoria', 'proveedor')},
        ),
    ]
