# Generated by Django 5.2.7 on 2025-11-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['nombre'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'ordering': ['categoria__nombre', 'nombre'], 'verbose_name': 'Sub-categoría', 'verbose_name_plural': 'Sub-categorías'},
        ),
    ]
