# Generated by Django 5.2.7 on 2025-11-12 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_articulo_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together={('nombre', 'subcategoria')},
        ),
        migrations.AddField(
            model_name='entradaarticulo',
            name='numero_proveedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Proveedor (Factura/SKU)'),
        ),
        migrations.AddField(
            model_name='entradaarticulo',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='almacen.proveedor', verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='numero_proveedor',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='proveedor',
        ),
    ]
